# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

people_list = [
["	Numbat	",	100	,"	Yellow	","	Purple	","	Female	",	2	],
["	Sunbird, lesser double-collared	",	37	,"	Teal	","	Crimson	","	Male	",	1	],
["	Snake, racer	",	96	,"	Fuscia	","	Pink	","	Male	",	2	],
["	White-fronted bee-eater	",	72	,"	Teal	","	Violet	","	Female	",	2	],
["	Arctic ground squirrel	",	12	,"	Violet	","	Pink	","	Male	",	1	],
["	Macaque, pig-tailed	",	78	,"	Aquamarine	","	Purple	","	Female	",	1	],
["	Openbill, asian	",	57	,"	Orange	","	Aquamarine	","	Female	",	1	],
["	Turtle, long-necked	",	58	,"	Khaki	","	Pink	","	Male	",	1	],
["	Stork, jabiru	",	28	,"	Teal	","	Violet	","	Male	",	2	],
["	Purple moorhen	",	74	,"	Purple	","	Green	","	Male	",	1	],
["	Oribi	",	46	,"	Violet	","	Green	","	Female	",	1	],
["	Gull, swallow-tail	",	15	,"	Mauv	","	Pink	","	Male	",	1	],
["	Cape white-eye	",	76	,"	Turquoise	","	Fuscia	","	Male	",	1	],
["	Striped hyena	",	100	,"	Goldenrod	","	Khaki	","	Male	",	1	],
["	North American river otter	",	85	,"	Crimson	","	Turquoise	","	Female	",	1	],
["	Waved albatross	",	19	,"	Mauv	","	Goldenrod	","	Male	",	1	],
["	Small-toothed palm civet	",	78	,"	Goldenrod	","	Blue	","	Male	",	2	],
["	American alligator	",	63	,"	Yellow	","	Green	","	Female	",	1	],
["	Antelope, sable	",	93	,"	Khaki	","	Violet	","	Female	",	1	],
["	Admiral, indian red	",	82	,"	Maroon	","	Teal	","	Female	",	1	],
["	Lizard, blue-tongued	",	48	,"	Pink	","	Indigo	","	Female	",	2	],
["	Black-collared barbet	",	27	,"	Orange	","	Orange	","	Female	",	1	],
["	Little blue penguin	",	38	,"	Puce	","	Violet	","	Female	",	2	],
["	Eurasian badger	",	19	,"	Pink	","	Khaki	","	Female	",	2	],
["	Agouti	",	24	,"	Pink	","	Pink	","	Female	",	2	],
["	Red deer	",	33	,"	Pink	","	Indigo	","	Female	",	2	],
["	Meerkat	",	96	,"	Turquoise	","	Purple	","	Female	",	1	],
["	Hedgehog, south african	",	60	,"	Teal	","	Puce	","	Female	",	2	],
["	Long-tailed spotted cat	",	46	,"	Blue	","	Violet	","	Female	",	2	],
["	White-necked stork	",	31	,"	Indigo	","	Yellow	","	Male	",	2	],
["	Zorro, common	",	68	,"	Fuscia	","	Fuscia	","	Female	",	1	],
["	Fox, pampa gray	",	48	,"	Teal	","	Purple	","	Male	",	1	],
["	Boar, wild	",	42	,"	Aquamarine	","	Purple	","	Female	",	2	],
["	Greylag goose	",	37	,"	Yellow	","	Red	","	Male	",	2	],
["	Ring-necked pheasant	",	76	,"	Pink	","	Turquoise	","	Female	",	1	],
["	Oryx, beisa	",	66	,"	Indigo	","	Puce	","	Male	",	1	],
["	Swan, trumpeter	",	95	,"	Blue	","	Teal	","	Female	",	2	],
["	Gerbil (unidentified)	",	82	,"	Pink	","	Blue	","	Female	",	2	],
["	Deer, roe	",	80	,"	Violet	","	Orange	","	Male	",	2	],
["	Phascogale, brush-tailed	",	47	,"	Mauv	","	Green	","	Male	",	1	],
["	Rabbit, eastern cottontail	",	66	,"	Aquamarine	","	Teal	","	Female	",	1	],
["	Constrictor, eastern boa	",	20	,"	Turquoise	","	Yellow	","	Female	",	1	],
["	Turaco, violet-crested	",	61	,"	Pink	","	Crimson	","	Male	",	1	],
["	Badger, eurasian	",	77	,"	Violet	","	Blue	","	Female	",	2	],
["	Booby, masked	",	74	,"	Turquoise	","	Aquamarine	","	Male	",	2	],
["	Green-backed heron	",	31	,"	Crimson	","	Aquamarine	","	Female	",	1	],
["	Anteater, australian spiny	",	52	,"	Crimson	","	Blue	","	Female	",	1	],
["	Heron, green-backed	",	84	,"	Khaki	","	Puce	","	Male	",	1	],
["	Rattlesnake, horned	",	34	,"	Maroon	","	Yellow	","	Female	",	1	],
["	Pintail, white-cheeked	",	74	,"	Puce	","	Orange	","	Male	",	1	],
["	American beaver	",	98	,"	Green	","	Green	","	Female	",	1	],
["	Arctic tern	",	43	,"	Fuscia	","	Blue	","	Male	",	2	],
["	European wild cat	",	76	,"	Pink	","	Pink	","	Male	",	2	],
["	Gray langur	",	32	,"	Purple	","	Yellow	","	Female	",	2	],
["	Racer, blue	",	57	,"	Purple	","	Fuscia	","	Male	",	2	],
["	Swallow-tail gull	",	66	,"	Crimson	","	Turquoise	","	Male	",	2	],
["	Alligator, mississippi	",	78	,"	Mauv	","	Green	","	Male	",	2	],
["	Parakeet, rose-ringed	",	45	,"	Maroon	","	Puce	","	Female	",	2	],
["	Common brushtail possum	",	83	,"	Maroon	","	Goldenrod	","	Male	",	1	],
["	Common dolphin	",	26	,"	Puce	","	Goldenrod	","	Male	",	2	],
["	Dolphin, bottle-nose	",	58	,"	Pink	","	Purple	","	Male	",	2	],
["	Indian jackal	",	57	,"	Khaki	","	Aquamarine	","	Female	",	1	],
["	Suricate	",	27	,"	Goldenrod	","	Teal	","	Male	",	2	],
["	African elephant	",	57	,"	Mauv	","	Purple	","	Male	",	1	],
["	Red-winged hawk (unidentified)	",	45	,"	Goldenrod	","	Pink	","	Female	",	1	],
["	Savanna fox	",	31	,"	Aquamarine	","	Pink	","	Male	",	1	],
["	Albatross, waved	",	3	,"	Aquamarine	","	Puce	","	Male	",	1	],
["	Chilean flamingo	",	99	,"	Blue	","	Red	","	Female	",	1	],
["	Plover, blacksmith	",	40	,"	Pink	","	Teal	","	Female	",	1	],
["	Vervet monkey	",	79	,"	Puce	","	Goldenrod	","	Male	",	2	],
["	Prehensile-tailed porcupine	",	66	,"	Fuscia	","	Crimson	","	Male	",	2	],
["	Waved albatross	",	73	,"	Teal	","	Goldenrod	","	Female	",	2	],
["	African skink	",	52	,"	Red	","	Indigo	","	Male	",	1	],
["	Bustard, stanley	",	45	,"	Red	","	Fuscia	","	Female	",	1	],
["	Stork, jabiru	",	10	,"	Pink	","	Crimson	","	Female	",	1	],
["	Common turkey	",	24	,"	Teal	","	Maroon	","	Male	",	1	],
["	Sacred ibis	",	24	,"	Red	","	Khaki	","	Male	",	2	],
["	Agile wallaby	",	74	,"	Yellow	","	Orange	","	Female	",	2	],
["	Vulture, white-rumped	",	81	,"	Mauv	","	Crimson	","	Female	",	2	],
["	Badger, honey	",	12	,"	Violet	","	Orange	","	Female	",	2	],
["	Starling, superb	",	78	,"	Teal	","	Turquoise	","	Male	",	2	],
["	Roe deer	",	2	,"	Red	","	Aquamarine	","	Male	",	2	],
["	South American puma	",	97	,"	Puce	","	Khaki	","	Male	",	2	],
["	Legaan, water	",	33	,"	Orange	","	Aquamarine	","	Male	",	2	],
["	Curve-billed thrasher	",	79	,"	Indigo	","	Orange	","	Female	",	1	],
["	Dove, mourning collared	",	72	,"	Goldenrod	","	Blue	","	Female	",	2	],
["	Turkey, australian brush	",	97	,"	Goldenrod	","	Indigo	","	Male	",	2	],
["	Gambel's quail	",	81	,"	Purple	","	Violet	","	Female	",	2	],
["	Galapagos penguin	",	69	,"	Puce	","	Yellow	","	Male	",	2	],
["	Giraffe	",	67	,"	Maroon	","	Crimson	","	Female	",	2	],
["	Nile crocodile	",	52	,"	Fuscia	","	Khaki	","	Male	",	1	],
["	Crane, brolga	",	47	,"	Violet	","	Indigo	","	Female	",	2	],
["	Lizard, collared	",	75	,"	Goldenrod	","	Violet	","	Male	",	1	],
["	Monitor, water	",	3	,"	Yellow	","	Violet	","	Male	",	2	],
["	Agile wallaby	",	68	,"	Red	","	Khaki	","	Male	",	2	],
["	Sage hen	",	35	,"	Orange	","	Mauv	","	Female	",	1	],
["	Owl, burrowing	",	50	,"	Purple	","	Crimson	","	Female	",	2	],
["	Tiger cat	",	27	,"	Maroon	","	Violet	","	Female	",	1	],
["	Indian mynah	",	7	,"	Mauv	","	Green	","	Female	",	1	],
["	Eagle, african fish	",	41	,"	Pink	","	Puce	","	Female	",	1	]
]

people_list.each do |name, age, hair_color, eye_color, gender, alive|
  Person.create( name: name, age: age, hair_color: hair_color, eye_color: eye_color, gender: gender, alive: alive)
end 

